title: My blog for learning
author: Paul
email: devolvaper@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I would lern to code and code to learn!

# social links
twitter_username: your-twitter-handle
github_username:  olvap1309

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
